# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-30 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='user0', max_length=20),
        ),
    ]
